name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    environment: npm

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run version patch
    - run: npm run publish
